@ECHO OFF
echo VERTEX HELP CENTER
echo 1: EVENT EDITOR
echo IF YOU ARE CONFUSING OR DO NOT KNOW ABOUT THE EVENT EDITOR,
echo SO IN THE EDITOR YOU WILL SEE 10 EMPTY EVENTS
echo YOU CAN EDIT IT AND TURN IT TO ANY EVENT.
echo IN AN EVENT, IT HAD CONDITION AND EXPRESSION.
echo 2: PROPERTIES
echo PROPERTIES HAD MANY OPTIONS IN IT, YOU MUST READ AND ENTER THE EMPTY BOX.
echo 3: COMPILER
echo WE USED C# COMPILER AND C# TO COMPILE THE GAME CODE.
echo 4: BUGS
echo WE WILL FIX IT RIGHT AWAY.
pause